import "./globals.css";
import Sidebar from "./home/sidebar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Sidebar />
        <main className=" md:pl-17">{children}</main>
      </body>
    </html>
  );
}
